## 03. NumPy

- N-dimensional array
- Random number generation (random sampling)
- Vectorized operations
- Linear algebra
- Probability distributions
- Statistical analysis
- np.NaN (similar to the Python None, represents a missing/null/non-existent value)

#### 1. Random number generation

In [1]:
# generate and print 100 random number between 0 and 9 using Python standard library random
import random
x = []
for i in range(100):
    x.append(random.randint(0,9))     # Python random standard library generate one random number at a time
print(x)


[3, 4, 7, 7, 4, 0, 7, 2, 2, 3, 1, 6, 1, 5, 1, 8, 7, 4, 1, 5, 5, 8, 3, 1, 8, 8, 0, 7, 5, 0, 2, 1, 2, 7, 6, 5, 5, 1, 5, 5, 7, 1, 6, 1, 0, 4, 0, 2, 4, 8, 8, 1, 7, 3, 6, 0, 8, 1, 9, 9, 9, 0, 5, 9, 9, 5, 8, 7, 8, 8, 1, 7, 9, 2, 5, 7, 4, 7, 4, 7, 8, 0, 9, 3, 4, 2, 8, 7, 0, 0, 2, 7, 4, 5, 1, 0, 1, 5, 6, 8]


In [2]:
type(x)

list

In [4]:
import numpy as np
y = np.array(x)
type(y)

numpy.ndarray

In [5]:
print(y)

[3 4 7 7 4 0 7 2 2 3 1 6 1 5 1 8 7 4 1 5 5 8 3 1 8 8 0 7 5 0 2 1 2 7 6 5 5
 1 5 5 7 1 6 1 0 4 0 2 4 8 8 1 7 3 6 0 8 1 9 9 9 0 5 9 9 5 8 7 8 8 1 7 9 2
 5 7 4 7 4 7 8 0 9 3 4 2 8 7 0 0 2 7 4 5 1 0 1 5 6 8]


In [6]:
# generate and print 100 random number between 0 and 9 using NumPy
import numpy as np
z = np.random.randint(0,10,100)   # Numpy can generate many random number efficiently
print(z)
type(z)

[9 0 4 2 6 2 3 3 9 4 9 1 8 1 2 3 8 6 3 0 1 3 4 4 4 8 5 4 4 3 8 4 9 1 3 1 4
 9 8 9 9 3 3 6 0 6 2 6 8 4 1 5 7 8 6 8 9 2 4 6 3 0 0 9 9 9 7 6 9 8 4 0 7 0
 4 6 0 7 6 1 0 9 4 7 4 5 5 4 5 4 0 4 5 2 1 3 5 1 1 5]


numpy.ndarray

#### 2. Creation of a NumPy Array
- create an array from a list
- create an array of randomly generated numbersnp.random.randint()
- create an array using arange(start, stop, step, dtype)
- create an array using np.linspace(start, stop, number of values)

In [4]:
# create an array from a list - method #1
z = np.array(x)
print(z)

[0 8 3 4 7 8 7 8 5 0 8 0 7 8 3 8 6 0 0 0 1 0 0 5 0 5 6 0 5 5 4 7 1 4 4 4 4
 3 6 4 0 8 9 7 1 6 7 9 4 1 0 1 4 6 7 8 9 5 6 1 8 3 8 5 5 6 9 3 1 6 9 1 2 4
 1 6 0 5 0 4 8 7 1 1 9 3 2 3 4 1 5 6 5 2 0 7 6 7 3 9]


In [5]:
# convert a list to an array - method #2
z = np.asarray(x)
print(z)

[0 8 3 4 7 8 7 8 5 0 8 0 7 8 3 8 6 0 0 0 1 0 0 5 0 5 6 0 5 5 4 7 1 4 4 4 4
 3 6 4 0 8 9 7 1 6 7 9 4 1 0 1 4 6 7 8 9 5 6 1 8 3 8 5 5 6 9 3 1 6 9 1 2 4
 1 6 0 5 0 4 8 7 1 1 9 3 2 3 4 1 5 6 5 2 0 7 6 7 3 9]


In [6]:
# create an array of randomly generated numbersnp.random.randint() #3
z = np.random.randint(0,10,100)  
print(z)

[5 1 9 4 8 6 3 0 6 1 8 9 8 9 8 8 5 5 0 3 8 6 4 6 9 6 8 3 4 7 5 0 2 1 3 0 9
 7 4 8 3 2 8 7 8 9 9 5 6 1 0 4 2 3 4 3 7 2 2 3 5 9 3 7 9 2 0 3 3 3 0 5 6 7
 0 7 1 1 6 9 9 8 8 1 5 1 8 4 1 4 2 9 5 7 3 2 6 6 7 6]


In [7]:
# create an array using arange(start, stop, step, dtype) #4
z = np.arange(10, 100, 10, np.float64)
print(z)

[10. 20. 30. 40. 50. 60. 70. 80. 90.]


In [8]:
# create an array using np.linspace(start, stop, number of values) #5
z = np.linspace(10, 20, 5)
print(z)

[10.  12.5 15.  17.5 20. ]


#### 3. Operations
- shape: the structure of the array
- reshape(): change the structure of the array
- ndim: number of dimensions
- size: number of elements
- itemsize: the size in bytes of the element
- dtype: the data type of the element
- \[row,colum\] or \[row\]\[column\]: retrieve an item from an array based on its position
- sum(), mean(), median(), min(), max(), var(), std()

In [8]:
a = np.random.randint(0,10,24)
print(a)

[5 0 4 7 4 5 7 2 7 4 9 3 2 3 5 8 7 0 8 7 7 7 9 6]


In [9]:
a.shape

(24,)

In [10]:
a.sum()    # compare with Python sum(list)

126

In [11]:
np.sum(a), np.mean(a), np.min(a), np.max(a), np.var(a), np.std(a), np.median(a)

(126, 5.25, 0, 9, 6.520833333333333, 2.553592241007427, 5.5)

In [12]:
b = a.reshape(4,6)
print(b)

[[5 0 4 7 4 5]
 [7 2 7 4 9 3]
 [2 3 5 8 7 0]
 [8 7 7 7 9 6]]


In [13]:
print(b.shape)

(4, 6)


In [14]:
b.size

24

In [15]:
b.ndim

2

In [16]:
b.itemsize

4

In [17]:
b.dtype

dtype('int32')

In [18]:
# access an element in an array - method #1
b[2,3]

8

In [14]:
# access an element in an array - method #2
b[0][0]

4